<?php 
$data = $this->getData();
?>
<form name="frm_payment_method_paypal" action="<?php echo $data['action']; ?>" method="POST">
	<input type="hidden" name="business" value="<?php echo $data['merchant_email']; ?>" />
	<input type="hidden" name="cmd" value="_xclick" />
	<input type="hidden" name="item_name" value="<?php echo $data['product_name']; ?>" />
	<input type="hidden" name="item_number" value="1" />
	<input type="hidden" name="handling" value="0" />
	<input type="hidden" name="currency_code" value="<?php echo $data['currency_code']; ?>" />
	<input type="hidden" name="amount" value="<?php echo $data['amount']; ?>" />
	<input type="hidden" name="no_shipping" value="1" />
	<input type="hidden" name="cancel_return" value="<?php echo $data['cancel_url']; ?>" />
	<input type="hidden" name="return" value="<?php echo $data['callback_url']; ?>" />
	<script >
		setTimeout("document.frm_payment_method_paypal.submit()", 1);
	</script>
</form>
