<?php 
$collections = $this->getCommissionCollection();

//echo "<pre>"; print_r($collections->getData()); die;

?>
<div class="aff-main-content col-lg-12 col-md-12 col-sm-12 col-xs-12">

<?php if ($collections && count($collections)): ?>
    <div class="affiliate-order">
         <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Updated date') ?></th>
                    <th scope="col" class="col commission"><?php /* @escapeNotVerified */ echo __('Commission Total') ?></th>
                    <th scope="col" class="col order-total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                    <th scope="col" class="col price"><?php /* @escapeNotVerified */ echo __('Price total of Orders') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php 
            $total = 0;
            foreach ($collections as $_collection) : ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $_collection->getCreateAt() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Commission Total')) ?>" class="col commission"><?php /* @escapeNotVerified */ echo $block->formatCurrency($_collection->getCommission()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col order-total"><?php /* @escapeNotVerified */ echo $_collection->getOrderTotal() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Price total of Orders')) ?>" class="col price"><?php /* @escapeNotVerified */ echo $block->formatCurrency($_collection->getPriceOrderTotal()) ?></td>
                </tr>
                <?php $total += $_collection->getCommission();?>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div><strong>Total: <?php echo $block->formatCurrency($total);?></strong></div>
    </div>
    
<?php else: ?>
    <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no commission.'); ?></span></div>
<?php endif ?>
</div>
