<?php
$_helper = $this->getHelper();
$collection  = $block->getCampaignCollection();
$count       = $collection->count();
$size        = $collection->getSize();
$limit       = $block->getLimit();
$currentPage = $block->getCurrentPage();
$start       = $size - (($currentPage - 1) * $limit);
?>
<div class="aff-main-content col-lg-12 col-md-12 col-sm-12 col-xs-12">

    <?php if ($collection && count($collection)): ?>
        <div class="affiliate-order">
            <table class="data table table-invitation-history-items history" id="my-invitation-history-table">
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Affiliate Programs') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Id') ?></th>
                    <th scope="col" class="col customer_email_address"><?php /* @escapeNotVerified */ echo __('Campaign') ?></th>
                    <th scope="col" class="col expiry_date_commission"><?php /* @escapeNotVerified */ echo __('Start Date') ?></th>
                    <th scope="col" class="col expiry_date_commission"><?php /* @escapeNotVerified */ echo __('End Date') ?></th>
                    <th scope="col" class="col expiry_date_commission"><?php /* @escapeNotVerified */ echo __('Total Commission') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php
                $total = 0;
                foreach ($collection as $_collection) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Id')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_collection->getId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Campaign')) ?>" class="col"><?php /* @escapeNotVerified */ echo $_collection->getName() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Start Date')) ?>" class="col"><?= date('d-m-Y', strtotime($_collection->getFromDate())); ?></td>
                        <td data-th="<?= $block->escapeHtml(__('End Date')) ?>" class="col"><?= date('d-m-Y', strtotime($_collection->getToDate())); ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Total Commission')) ?>" class="col"><?= $this->getTotalCommission($_collection->getTrackingCode()); ?></td>
                    </tr>
                    <!-- Modal -->
                    <div id="myModal<?=$_collection->getId()?>" class="modal fade" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Modal Header</h4>
                                </div>
                                <div class="modal-body">
                                    <p>Some text in the modal.</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>

                        </div>
                    </div>
                    <?php $total += $_collection->getCommissionTotal();?>
                <?php endforeach; ?>
                </tbody>
            </table>
            <?= $block->getChildHtml('toolbar'); ?>
        </div>

    <?php else: ?>
        <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no programs.'); ?></span></div>
    <?php endif ?>
</div>
