<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$email = $customerSession->getCustomer()->getEmail();
?>
<div class="aff-main-content col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="affiiate-page-title">
        <h1><?php echo __('Register')?></h1>
    </div>
    <form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?php if($customerSession->isLoggedIn() && empty($block->checkAccountExist($email))):?>
        <fieldset class="fieldset create info">
            <h3>Name: <?php echo $customerSession->getCustomer()->getName();  ?></h3>
            <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
            <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        </fieldset>
    <?php else: ?>
         <fieldset class="fieldset create info">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
            <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
            <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
            <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
             <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
            <?php endif ?>
            <div class="field required">
                <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" onchange="checkEmailRegister('<?php echo $block->getCheckEmailUrl();?>')">
                    <div id="affiliate_message_hidden_email" class="affiliate_message"></div>
                    <div id="affiliate-please-wait-email" style="display:none"><span><?php echo __('Checking Email ...')?></span></div>

                </div>
            </div>
        </fieldset>
        <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend><br>

            <div class="field password required">
                <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                <div class="control">
                    <input type="password" name="password" id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" data-validate="{required:true, 'validate-password':true}" autocomplete="off">
                </div>
            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
                <div class="control">
                    <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>
            <?php echo $block->getChildHtml('form_additional_info'); ?>
        </fieldset>
    <?php endif; ?>
    <?php //if ($block->getShowAddressFields()): ?>
            <fieldset class="fieldset address">
                <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
                <input type="hidden" name="create_address" value="1" />
                <div class="field company">
                    <label for="company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                    <div class="control">
                        <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                    </div>
                </div>
                <div class="field required telephone">
                    <label for="telephone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                    <div class="control">
                        <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                    </div>
                </div>

                <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                <div class="field street required">
                    <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                    <div class="control">
                        <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                        <div class="nested">
                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                            <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                <div class="field additional">
                                    <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                                    </label>
                                    <div class="control">
                                        <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                    </div>
                                </div>
                            <?php endfor; ?>
                        </div>
                    </div>
                </div>

                <div class="field required">
                    <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                    <div class="control">
                        <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                    </div>
                </div>

                <div class="field region required">
                    <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                    <div class="control">
                        <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                            <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                        </select>
                        <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                    </div>
                </div>

                <div class="field zip required">
                    <label for="zip" class="label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                    <div class="control">
                        <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                    </div>
                </div>

                <div class="field country required">
                    <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                    <div class="control">
                        <?php echo $block->getCountryHtmlSelect() ?>
                    </div>
                </div>
                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                <?php if ($addressAttributes): ?>
                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                    <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                <?php endif;?>
                <input type="hidden" name="default_billing" value="1">
                <input type="hidden" name="default_shipping" value="1">
            </fieldset>

        <?php //endif; ?>
        <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Affiliate Information') ?></span></legend><br>

            <div class="field refering_website required">
                <label for="refering_website" class="label"><span><?php /* @escapeNotVerified */ echo __('Refering Website') ?></span></label>
                <div class="control">
                    <input type="text" name="refering_website" id="refering_website" title="<?php /* @escapeNotVerified */ echo __('Refering Website') ?>" class="input-text" data-validate="{required:false, 'validate-url':true}" autocomplete="off" value="http://abc.com">
                </div>
            </div>

            <div class="field tax_id">
                <label for="tax_id" class="label"><span><?php /* @escapeNotVerified */ echo __('Tax ID') ?></span></label>
                <div class="control">
                    <input type="text" name="tax_id" id="tax_id" title="<?php /* @escapeNotVerified */ echo __('Tax ID') ?>" class="input-text" data-validate="{required:false}">
                </div>
            </div>

            <?php echo $this->getChildHtml("check.list.payments"); ?>
            <!--
            <div class="field payment paypal_email">
                <label for="paypal_email" class="label"><span><?php /* @escapeNotVerified */ echo __('Paypal Email') ?></span></label>
                <div class="control">
                    <input type="text" name="paypal_email" id="paypal_email" title="<?php /* @escapeNotVerified */ echo __('Paypal Email') ?>" class="input-text" data-validate="{required:false, 'validate-email':true}" autocomplete="off">
                </div>
            </div>

            <div class="field payment skrill_email">
                <label for="skrill_email" class="label"><span><?php /* @escapeNotVerified */ echo __('Skrill Email') ?></span></label>
                <div class="control">
                    <input type="text" name="skrill_email" id="skrill_email" title="<?php /* @escapeNotVerified */ echo __('Skrill Email') ?>" class="input-text" data-validate="{required:false, 'validate-email':true}" autocomplete="off">
                </div>
            </div>
            <div class="field payment braintree_id">
                <label for="braintree_id" class="label"><span><?php /* @escapeNotVerified */ echo __('Braintree Merchant Account Id') ?></span></label>
                <div class="control">
                    <input type="text" name="braintree_id" id="braintree_id" title="<?php /* @escapeNotVerified */ echo __('Braintree Merchant Account Id') ?>" class="input-text" data-validate="{required:false}" autocomplete="off">
                </div>
            </div>
            -->
            <?php echo $this->getChildHtml("extra.payments"); ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
            </div>
        </div>
    </form>
</div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
    
    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php //if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<script type="text/javascript">
function checkEmailRegister(requestUrl) {
            require([
                'jquery'
            ], function  ($j) {
                var email_address = $j('#email_address').val();
                var email = email_address.trim();
                if(email) {
                //     var params = {email_address: email_address};
                    $j('#affiliate-please-wait-email').show();
                    $j('#affiliate_message_hidden_email').hide();
                    $j.ajax({
                        url: requestUrl,
                        type: 'get',
                        data: {email_address: email_address},
                        complete: function (xhr) {
                            endCheckEmailRegister();
                            $j('#affiliate_message_hidden_email').html(xhr.responseText);
                        },
                        error: function (xhr, status, errorThrown) {
                        }
                    });
                } else {
                    $j('#affiliate_message_hidden_email').hide();
                }
            });
        }
function endCheckEmailRegister() {
            require([
                'jquery'
            ], function  ($j) {
                $j('#affiliate-please-wait-email').hide();
                $j('#affiliate_message_hidden_email').show();
                var is_invalid_email = $j('#is_valid_email').val();
                
            });
        }
    </script>
<?php //endif; ?>
